######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 18 10:24:08 2013
######################################################################

TEMPLATE = subdirs

# Input
SUBDIRS += test_codec \
            test_qtLibraryTarget

QMAKE_CLEAN += Makefile
