######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 30 14:17:27 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

CONFIG += console

QMAKE_CLEAN += Makefile
QMAKE_CLEAN += textcode
