######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 31 14:53:33 2013
######################################################################

TEMPLATE = lib
TARGET = $$qtLibraryTarget(tangke)
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
QMAKE_CLEAN += Makefile Makefile.Debug Makefile.Release
QMAKE_CLEAN += -r debug
QMAKE_CLEAN += -r release
QMAKE_CLEAN += lib*
VERSION = 4.0.0
